# This workflows will upload a Python Package using Twine when a release is created

name: tests

on: push

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Install openslide
        run: sudo apt-get install openslide-tools
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools tox tox-gh-actions
      - name: Test with tox
        run: tox

  # minimizing matrix by only testing 3.9 on mac & windows
  mac-win:
    name: ${{ matrix.platform }} (3.9)
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        # platform [macos-latest, windows-latest] 
        platform: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install openslide on mac
        if: ${{ matrix.platform == 'macos-latest' }}
        run: brew install openslide
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools tox tox-gh-actions
      - name: Test with tox
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}

  deploy:
    needs: [ubuntu-latest, mac-win]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
        run: |
          git tag
          python -m build .
          twine upload dist/*
